language: node_js
sudo: false

node_js: stable
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - yarn global add coveralls nyc

script:
  - yarn test

after_success:
  - cat ./coverage/lcov.info | coveralls
  - yarn semantic-release
